-- Import stakeholder list
insert into stakeholders (email, full_name) values
('nagarjuna@iisc.ac.in', 'PITTY NAGARJUNA'),
('trherradura@dlsud.edu.ph', 'Herradura, Tita'),
('kyneandrewhao@gmail.com', 'Hao, Kyne'),
('trishajeanramos@gmail.com', 'Ramos, Trisha Jean'),
('ramesesluis@gmail.com', 'Barria, Rameses'),
('dylanpilapil2@gmail.com', 'Pilapil, Marc Dylan Myles'),
('jgebron@mcl.edu.ph', 'EBRON, JONALYN'),
('17100409@usc.edu.ph', 'Guirnela, Ervin Joshua L.'),
('cstaromana@cit.edu', 'Sta. Romana, Cherry Lyn C.'),
('vonalphonse.godinez@cit.edu', 'Godinez, Von Alphonse'),
('nathaniel.arbasto@cit.edu', 'Arbasto, Nathaniel'),
('citmatth426@gmail.com', 'Contreras, Mattheus Marcus'),
('roddneilgemina@gmail.com', 'Gemina, Roddneil'),
('gabriel_ocampo@dlsu.edu.ph', 'Ocampo, Gabriel Vince'),
('alroy_reyes@dlsu.edu.ph', 'Reyes, Alroy Leon P.'),
('kikochan21@gmail.com', 'Jakosalem, Carlos Miguel'),
('vhonneluigi@gmail.com', 'Cuya, Vhonne Luigi B.'),
('nmpmunez@gmail.com', 'Paglinawan-Muñez, Neila'),
('rale.abrenica@gmail.com', 'Abrenica, Francis Rale M.'),
('lisajuress@gmail.com', 'Wang, Lisa Juress'),
('hcantonio1@up.edu.ph', 'Antonio, Harold'),
('raphael.gonda@dlsu.edu.ph', 'Gonda, Raphael'),
('evidal@ateneo.edu', 'Vidal, Eric Cesar Jr. E.'),
('judith.azcarraga@dlsu.edu.ph', 'Azcarraga, Judith'),
('cabansaynm@gmail.com', 'Cabansay, Nathaniel'),
('mpontiveros@up.edu.ph', 'Pontiveros, Marc Jermaine'),
('felisabascug@gmail.com', 'Bascug, Felisa Melanie Fay'),
('x-mendoza@live.com', 'Mendoza, Basil Xavier'),
('thomasdanjom.manulat@gmail.com', 'Manulat, Thomas Danjo'),
('zakfloreta20@gmail.com', 'Floreta, Zak'),
('mrodrigo@ateneo.edu', 'Rodrigo, Maria Mercedes'),
('brix.bitayo@gmail.com', 'Bitayo, Brix'),
('rmramirez4@up.edu.ph', 'Ramirez, Ronnie II'),
('derrickbinangbang1@gmail.com', 'Binangbang, Derrick'),
('jethomictin@gmail.com', 'Omictin, Jether'),
('sealtiel_dy@dlsu.edu.ph', 'Dy, Sealtiel'),
('angelcambarijan1009@gmail.com', 'Cambarijan, Angel Sheinen'),
('repuestocharlene@gmail.com', 'Repuesto, Charlene'),
('jakebajo21@gmail.com', 'Bajo, Jake'),
('hnadorna@up.edu.ph', 'Adorna, Henry'),
('caryl.chan@student.ateneo.edu', 'Chan, Caryl Rae'),
('cyzero69@gmail.com', 'Talip'),
('reneerosary.pintor@gmail.com', 'Pintor, Renee Rosary'),
('kyle_lasala@dlsu.edu.ph', 'Lasala, Kyle Carlo'),
('mmlimbo@up.edu.ph', 'Limbo, Moses'),
('fgbernardez@up.edu.ph', 'BERNARDEZ, Fernand; TORRES, Francis Luis'),
('paulmabellana@gmail.com', 'Abellana, Paul Thomas'),
('francis1272003@gmail.com', 'Chavez, Francis Benedict'),
('nate.que@student.ateneo.edu', 'Que, Nate Brevin'),
('silvalysha27@gmail.com', 'Silva, Lysha'),
('leighguanzonyata@gmail.com', 'Guanzon, Katelyn Leigh'),
('enrique.gomez@student.ateneo.edu', 'Gomez, Enrique Jose Stefan Pascual'),
('janeantoque7@gmail.com', 'Antoque, Jane'),
('nataviorani@gmail.com', 'Natavio, Rani Jay'),
('toraynoearljay06@gmail.com', 'Torayno, Earl Jay G.'),
('joshua_nicolai_gonzales@dlsu.edu.ph', 'Gonzales, Joshua Nicolai'),
('michelle.abarico@student.ateneo.edu', 'Abarico, Michelle'),
('mikaella_kaye_martinez@dlsu.edu.ph', 'Martinez, Mikaella Kaye A.'),
('ncbulio95@gmail.com', 'Bulio, Nice'),
('justin_rainier_go@dlsu.edu.ph', 'Go, Justin Rainier'),
('lorenz_marqueses@dlsu.edu.ph', 'Marqueses, Lorenz Bernard'),
('zbjimenez@up.edu.ph', 'Jimenez, Zechariah'),
('bfcalabia@up.edu.ph', 'Calabia, Bastian Nathaniel'),
('jsheffron@up.edu.ph', 'Heffron, Joaquin'),
('mscofficial2016@gmail.com', 'Cardaño, Mc Sergel'),
('asariafaye@gmail.com', 'Asaria, J Faye Champ A.'),
('beaux.consunji@student.ateneo.edu', 'Consunji, Beaux Nathania Immanuelle'),
('jbisanan@up.edu.ph', 'Isanan, Junel Alje'),
('lamberlainmuli@gmail.com', 'Muli, Lamberlain'),
('joshua.zapico@student.ateneo.edu', 'Zapico, Joshua'),
('23100502@usc.edu.ph', 'Linao, Carl Andrew'),
('roemer_caliboso@dlsu.edu.ph', 'Caliboso, Roemer Gabriel B.'),
('ninamargarette.catubig@cit.edu', 'Catubig, Niña Margarette'),
('ssdelacruz1@up.edu.ph', 'Dela Cruz, Shanmykel Ace'),
('emalino@nu-dasma.edu.ph', 'Aliño, Elmer M.'),
('acvicente@nu-dasma.edu.ph', 'Vicente, Alyssa'),
('aliabello@nu-dasma.edu.ph', 'Abello, Anna Lissa'),
('jdbravo@nu-dasma.edu.ph', 'Bravo, Jobert D.'),
('jbsoriano@up.edu.ph', 'Soriano, Jaymar'),
('jrmanaois@dlsud.edu.ph', 'Manaois, Jennylinde'),
('erquita.lallie@gmail.com', 'Erquita, Marnelli'),
('sdkamantigue@dlsud.edu.ph', 'Kamantigue, Sheryl'),
('vdnaraval@up.edu.ph', 'Naraval, Victor Dominic'),
('jjlipat@up.edu.ph', 'Lipat, Job'),
('lyleleon.butanas@g.msuiit.edu.ph', 'Butanas, Lyle Leon'),
('alrheemfabian@gmail.com', 'Fabian, Alrheem'),
('aira_garganera@dlsu.edu.ph', 'Garganera, Aira Jin'),
('ayanavila291@gmail.com', 'AVILA, IAN CELMAR A.'),
('rdroy@up.edu.ph', 'Roy, Rodrigo Emmanuel'),
('nigel_nograles@dlsu.edu.ph', 'Nograles, Nigel Roi'),
('kcbuno@up.edu.ph', 'Buño, Kelvin'),
('adarenas@up.edu.ph', 'Arenas, Angelo Gabriel D.'),
('maria.monica.manlises@gmail.com', 'Manlises, Maria Monica'),
('daphne_janelyn_go@dlsu.edu.ph', 'Go, Daphne Janelyn'),
('fpadao@southernleytestateu.edu.ph', 'Padao, Francis Rey'),
('ecabanig@southernleytestateu.edu.ph', 'Cabanig, Emmanueal'),
('kaguilar@southernleytestateu.edu.ph', 'Tablada, Khorina'),
('vmmadrid@up.edu.ph', 'Madrid, Val Randolf'),
('moltsolon@gmail.com', 'Solon, Malt John Vianney'),
('escanosimonlyster@gmail.com', 'Escaño, Simon Lyster'),
('aizernerevangelista@gmail.com', 'Evangelista, Kaye Aizerner'),
('avarconado@alum.up.edu.ph', 'Arco, Avdel'),
('abienfred.agarap@gcash.com', 'Agarap, Abien Fred'),
('miguel-a.aguinaldo@gcash.com', 'Aguinaldo, Miguel Anton'),
('kyutaper856@gmail.com', 'Bandiola, Kris Ian B.'),
('jugjorby825@gmail.com', 'Jugalbot, Jorby'),
('jeweleveve@gmail.com', 'Falcon, Geneveve'),
('kplanting@up.edu.ph', 'Lanting, Kurt'),
('hayabusagentrix@gmail.com', 'Balani, Axel'),
('karlo.orge@g.msuiit.edu.ph', 'Orge, Karlo'),
('baletejosiah@gmail.com', 'Balete, Immanuel Josiah')
on conflict (email) do nothing;